name: Get transcripts

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours

jobs:
  get_transcripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Or any version you'd like

      - name: Install dependencies
        run: |
          pip install youtube_transcript_api

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Run transcript retrieval script
        run: |
          python src/03-data_get_transcripts.py &
          SCRIPT_PID=$!
          sleep 7200  # Wait for 2 hours
          kill $SCRIPT_PID

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "got transcripts" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
